theme: jekyll-theme-primer
title: Andrea's homepage
description: Bookmark this to keep an eye on my project updates!

# Config
header_pages:
  - index.md
  - publications.md
  - research.md
  - repositories.md
  - cv.md
  - teaching.md
  - fieldwork.md
